export const CONNECT_TO_SERVER = "CONNECT_TO_SERVER";
export const RECIEVE_MESSAGE = "RECIEVE_MESSAGE";

export const FETCH_PUBLIC_ROOMS = 'FETCH_PUBLIC_ROOMS'
export const CREATE_ROOM = "CREATE_ROOM";
export const DELETE_ROOM = 'DELETE_ROOM'
export const JOIN_ROOM = "JOIN_ROOM";

export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";

export const UPDATE_USER = "UPDATE_USER";
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const REGISTER = "REGISTER"

export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const SET_ROOM_LIST_SORT_TECHNIQUE = 'SET_ROOM_LIST_SORT_TECHNIQUE'