export const CONNECT_TO_SERVER = "CONNECT_TO_SERVER";
export const RECIEVE_MESSAGE = "RECIEVE_MESSAGE";

export const CREATE_ROOM = "CREATE_ROOM";
export const JOIN_ROOM = "JOIN_ROOM";

export const UPDATE_USER_ID = "UPDATE_USER_ID";
